### ISSUE TITLE
Email invite contains wrong username

### ISSUE THREAD

**Issue by offiria** [offiria/offiria#12]
In this screenshot, "Admin" send the invite but shows up as "Super User"

![search_results_-_write2me_azrul com_-_azrul com_mail](https://f.cloud.github.com/assets/4747111/1054595/3e9baa00-110d-11e3-882e-6ef7ffec0f1d.png)

**Comment by JMSolo** [comment]
<h2>Solution</h2>

Open --> <em>youroffiriaroot-path</em> /components/com_account/templates/emailInvite.php<br />

<h5>Navigate to line #31 .. it will read as follows:</h5>

<div class="highlight"><pre><td style="background: #1A304D; padding: 21px 20px 19px; color: #fff; font-size:20px; font-weight: bold;">Invitation to <?php echo JText::_('CUSTOM_SITE_NAME');?> <span style="display: block; font-size: 15px; text-transform: normal; margin-top: 2px; font-weight: normal;">Super User is inviting you to join his site at <strong><?php echo JURI::base(); ?></strong> </span></td></pre></div><br />

<h5>Change to:</h5>

<div class="highlight"><pre><td style="background: #1A304D; padding: 21px 20px 19px; color: #fff; font-size:20px; font-weight: bold;">Invitation to <?php echo JText::_('CUSTOM_SITE_NAME');?> <span style="display: block; font-size: 15px; text-transform: normal; margin-top: 2px; font-weight: normal;"><?php echo $sender->get('name');?> is inviting you to join his site at <strong><?php echo JURI::base(); ?></strong> </span></td></pre></div><br />

<h3>Result Success</h3>

![username-on-invite](https://f.cloud.github.com/assets/5215074/1063104/40acdd0e-128a-11e3-8118-8bfdcbabf637.png)
Seems like it makes more sense to insert the actual username performing the invite rather than "Super" or "Admin".  Super is hardcoded into the invite rather than pulling from a lang file... so, this seems to be the clear and obvious fix.  
Correct me if I'm wrong please.. or if someone else finds a more appropriate method.. which.. this seems to already be the most logical.  Offiria / Azrul.. you can decide.

**Comment by offiria** [comment]
Do post a pull request, I'd be happy to accept it.
