### ISSUE TITLE
Department and Position in user bio page are shown as key-values

### ISSUE THREAD

**Issue by sauanimal** [offiria/offiria#23]
When viewing some users bio (/component/profile/?view=display&task=bio&user=…), the Department and Position values are not looked up with appropriate table. Instead of them – the department and position key values are shown.

**Comment by JMSolo** [comment]
Yeah, it would appear that the profile details are pulling in multiple values.  Hence, they are not being translated into their proper category names.. as you said.. only the value.

Within the database you can see the proper category names listed:
- off_stream_category = You will see the Type and Categories
- off_user_details = You can see the fields "work_department and work_position" and the Value is set as a text field next to it.

All Data Tables for Bio entries are being pulled through "< ?php echo '< div class="profile-data" >'; ? >".. So, it would seem that it is reading the value rather than translating the id text.  The only thing I have found is by manually converting the ID's through the database - or removing the Department and Position entries all together.

Thanks for pointing this out as we hadn't even noticed it and I agree this one certainly needs improvement.  When I have real time to spare I will help find a fix for this one.

:+1:

**Comment by offiria** [comment]
Added to 2.1.0 milestone

**Comment by sauanimal** [comment]
I wrote a workaround. It's not the nicest solution, but @this moment it works. Update the file as following components/com_profile/views/display/tmpl/bio.php

Line 3 add:

```
$category = new StreamCategory();
$depts = $category->getByCategory('department');
$positions = $category->getByCategory('position');
```

Line 35 replace 

```
// If it's not decoded it means it's not a multiple value field/array
echo StreamTemplate::escape($field->value);
```

with following code:

```
if ($field->fieldname == 'work_department' && !empty ($depts)) {
    // if it's department, lets fetch the value
    foreach ($depts as $dept) { if ($field->value == $dept->id) echo $dept->category; }
} elseif ($field->fieldname == 'work_position' && !empty ($positions)) {
    // if it's position, lets fetch the value
    foreach ($positions as $position) { if ($field->value == $position->id) echo $position->category; }
} else {
    // If it's not decoded it means it's not a multiple value field/array
    echo StreamTemplate::escape($field->value);
}
```

**Comment by JMSolo** [comment]
Good call pulling the values from the category.  We tested this on root install and sub-folder install and there is no consequence.  Works as it should.. new values (ie; departments and positions) can still be added / changed etc.  Furthermore, adding in these category filters will not interfere with other values pulled into the Bio. Submitted a pull request for further review.

Pull request is located Here:
https://github.com/offiria/offiria/pull/28

Also, this seems to be a "nice" solution as all it is doing is ensuring that the department and position values are separate from the adjacent info values which are all pulled in a singular manner.
