### ISSUE TITLE
Page-path part issue

### ISSUE THREAD

**Issue by sauanimal** [offiria/offiria#25]
The last item in the page-path part in a website is usually not item title, but "Message #..." (ie Home/Blog/Message #31). It would be rather proper, that its like Home/Blog/MyOpenedBlogPost...

And this is not only with blog but other type of entries also

Jan

**Comment by offiria** [comment]
The issue here is that each post has to actual "title" field. We can try to extract some info from the message itself but sometimes the message might start with random unexpected content, link, or hashtag etc, hence there is no reliable way of doing proper title. Hence, message id is the most reliable identifier that we have.

I'll keep this in mind, but it is not a high priority at this time.

**Comment by sauanimal** [comment]
I understand, it's more like a feature, rather than bug. One workable solution would be to add title field to all the items (ie blog, event, to-do etc)...and then use this field as a title field also in breadcrumbs...
