### ISSUE TITLE
Community analytics filtering button-order

### ISSUE THREAD

**Issue by sauanimal** [offiria/offiria#27]
In the community analytics page, there are filtering buttons (ie hour, day, week etc). The order seems not really logical: Hour, Week, Day, Month, Year

I would reccomend proper ordering: Hour, Day, Week, Month, Year.

**Comment by JMSolo** [comment]
I have submitted a Pull Request for this fix.  Here:
https://github.com/offiria/offiria/pull/29

It looks like it may had been an intentional ordering on their part as the code is pulling the "Day" filter as a default. In turn they placed it in the middle to maintain symmetry. This is just a guess however as the Group Case are all in the proper order.. the only thing not in the logical order is the means in which they pull from the tables.

I applied the proper order through the Pull Request for further review.

Please check and see the order and file changed for further clarity.
Didn't bother us so much.. although, some may be wanting proper ordering.

**Comment by offiria** [comment]
Fixed.. thanks!
