### ISSUE TITLE
Chat for friends type facebook

### ISSUE THREAD

**Issue by celu** [offiria/offiria#83]
Facebook has got a interesing chat for only friends, this idea will be good!

**Comment by celu** [comment]
Please add a chat :)

**Comment by offiria** [comment]
I am sorry, but we do not have plan to add chat features anytime soon. I will close this request for now.

**Comment by celu** [comment]
Why?

**Comment by JMSolo** [comment]
As I see it and for what purposes myself and clients first had shown a vested interest in the product, I can give my (personal) opinion as to why.  This product is a solution that is meant for more of an internal communication and collaboration platform for businesses and organizations.  It is not built on the premise (nor vision) of being integrated into environments that wish to achieve community type engagements.  Simply put.. a chat feature does not seem necessary in this circumstance as the software performs as it should.  Adding in an additional chat function would only take away from the "organized and documented" set that most would like to use this for.  Chat features (PHP implemented or otherwise) can be found on one's own accord.. but they take away from the desired functions.

This is just my rather extensive take on why.

**Comment by celu** [comment]
But offira can add a option in admin (Take on or off the chat)

**Comment by offiria** [comment]
@JMSolo explained it well. I'll just add to that.

We used to come from a very chat-centric evironment. (skype) and there are a few reasons we don't want to go back to that. 
- Chat is an "interruption" - based communication, which can be very disruptive to your workflow. 
- Chat is also terrible at capturing "knowledge" and making it searchable.
- Load on server will be tremendous. Implementing chat in php is very inefficient.

In a way, Offiria very existence is so that we don't have to deal with too much live chat really. If we execute this vision well, there should be little reason for using chat.
